services:
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
      target: development
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules
      - frontend_next:/app/.next
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://backend:3001
      - NEXT_TELEMETRY_DISABLED=1
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - backend
    command: pnpm dev

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: development
    ports:
      - "3001:3001"
    volumes:
      - ./backend:/app
      - backend_node_modules:/app/node_modules
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb://mongo:27017/sl3
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - mongo
    command: pnpm start:dev

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=sl3

volumes:
  mongodb_data:
  frontend_node_modules:
  frontend_next:
  backend_node_modules:
