services:
  mongodb:
    image: mongo:8.0.4
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - mongodb_config:/data/configdb
    networks:
      - sl3_network

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - sl3_network

volumes:
  mongodb_data:
    external: true
    name: "8bb487d2a73611a319a292f1ed489aa95617f3e1540824ccd5ef37e5feb067eb"
  mongodb_config:
    external: true
    name: "3465cf60da5edb50914449c3d2bca1c8f65956a079e59388efeaa146f9b97bbd"
  redis_data:

networks:
  sl3_network:
    driver: bridge